# Generated by Django 5.1.7 on 2025-03-20 15:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_traderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='General', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
