# Generated by Django 5.1.7 on 2025-03-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='preferred_trades',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
